image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-browser
    visibility: public
  - port: 3001
    onOpen: open-preview
    visibility: public
  - port: 5432
    onOpen: ignore
tasks:
  - before: nvm install 16.15.0
  - init: npm install

    openMode: split-right

vscode:
  extensions:
    - esbenp.prettier-vscode
